### ISSUE TITLE
Error message in homebridge log

### ISSUE THREAD

**Issue by eabakker** [ebaauw/homebridge-ups#1]
Running homebridge on Synology NAS in a docker container.
The UPS connected to the NAS  (192.168.86.180) is a PowerWalker VI STL 1500.

Currently using other nut plugin (Homebridge NUT (Network UPS Tools) )and that one works OK.

Upgraded node.js to latest version, 16.17.1.

Message popping up in log every 5 sec or so:

[9/25/2022, 11:12:00 PM] [UPS] 192.168.86.180: error: TypeError: constants.device.mfr.trim is not a function
    at UpsHost.init (/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:70:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UpsPlatform.init (/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:104:7)

**Comment by ebaauw** [comment]
What UPS device do you have?  Please list the output of `ups info`.  It looks like it doesn’t carry the `device.mfr` variable.

**Comment by eabakker** [comment]
Hi Erik,

it is a Powerwalker.com <http://powerwalker.com/> ups, model VI STL 1500 and connected to a Synology NAS. 

Don’t know how to do the ups info on Synology, in Control Panel it shows manufacturer 1 and Model 1500. That’s also what the other Homebridge plugin shows.

Erik

**Comment by ebaauw** [comment]
SSH into the Synology and run `ups info`.  At least that works for me, using the standard Homebridge package on DSM 7.2.

Alternatively, install Homebridge UPS on another system, and run `ups -H x.x.x.x info` from that system.  Make sure to list that system's IP address under _Permitted Synology NAS devices._.

**Comment by eabakker** [comment]
Run Homebridge in docker, so ran ups info from docker shell. Output attached below.

{
  "version": "Network UPS Tools upsd DSM7-1-42464-211216 - http://www.networkupstools.org/",
  "apiVersion": "1.2",
  "devices": {
    "ups": {
      "description": "Unavailable",
      "nCients": "1",
      "clients": [
        "127.0.0.1"
      ],
      "commands": [
        "beeper.disable",
        "beeper.enable",
        "beeper.mute",
        "beeper.off",
        "beeper.on",
        "load.off",
        "load.off.delay",
        "load.on",
        "load.on.delay",
        "shutdown.return",
        "shutdown.stayoff",
        "shutdown.stop",
        "test.battery.start.deep",
        "test.battery.start.quick",
        "test.battery.stop"
      ],
      "constants": {
        "battery.charge": 100,
        "battery.charge.low": 10,
        "battery.charge.warning": 20,
        "battery.mfr.date": 1,
        "battery.runtime": 7200,
        "battery.runtime.low": 300,
        "battery.type": "PbAcid",
        "battery.voltage": "27.1",
        "battery.voltage.nominal": 24,
        "device.mfr": 1,
        "device.model": 1500,
        "device.serial": "",
        "device.type": "ups",
        "driver.name": "usbhid-ups",
        "driver.parameter.pollfreq": 30,
        "driver.parameter.pollinterval": 5,
        "driver.parameter.port": "auto",
        "driver.parameter.synchronous": "no",
        "driver.version": "DSM7-1-42464-211216",
        "driver.version.data": "CyberPower HID 0.4",
        "driver.version.internal": "0.41",
        "input.transfer.high": 290,
        "input.transfer.low": 162,
        "input.voltage": "237.6",
        "input.voltage.nominal": 230,
        "output.voltage": "237.6",
        "ups.beeper.status": "enabled",
        "ups.delay.shutdown": 20,
        "ups.delay.start": 30,
        "ups.load": 0,
        "ups.mfr": 1,
        "ups.model": 1500,
        "ups.productid": 601,
        "ups.realpower.nominal": 900,
        "ups.serial": "",
        "ups.status": "OL",
        "ups.timer.shutdown": -60,
        "ups.timer.start": -60,
        "ups.vendorid": 764
      },
      "variables": {
        "battery.charge.low": 10,
        "battery.runtime.low": 300,
        "input.transfer.high": 290,
        "input.transfer.low": 162,
        "ups.delay.shutdown": 20,
        "ups.delay.start": 30
      }
    }
  }
}

**Comment by ebaauw** [comment]
Hm, it does carry `ups.mfr`, but it contains only digits, so Homebridge UPS incorrectly treats the value as an integer, but I can fix that.  Same for `ups.model`.  More worrying, it does report an empty `ups.serialnumber`, which I use as ID for the accessory.  Need to think what to do about that.

**Comment by ebaauw** [comment]
Could you try v1.0.1?  I should handle the number manufacturer name and model, as well as the empty serial number.  From what I can see from the output, Homebridge UPS should support it otherwise.

**Comment by eabakker** [comment]
Thanks for the quick update.Unfortunately it’s not working. I get the below message (sorry could only do screenshot from remote vpn session on Iphone)On 30 Sep 2022, at 11:12, Erik Baauw ***@***.***> wrote:﻿
Could you try v1.0.1?  I should handle the number manufacturer name and model, as well as the empty serial number.  From what I can see from the output, Homebridge UPS should support it otherwise.

**Comment by ebaauw** [comment]
No message?

**Comment by eabakker** [comment]
[9/30/2022, 5:12:14 PM] [UPS] 192.168.86.180: error: TypeError: Cannot read properties of undefined (reading 'trim')    at UpsHost.init (/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:74:49)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at UpsPlatform.init (/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:104:7)On 30 Sep 2022, at 17:06, Erik Baauw ***@***.***> wrote:﻿
No message?

**Comment by ebaauw** [comment]
Missing `device.firmware`.  Could you try beta v1.0.2-0?

**Comment by eabakker** [comment]
That looks much better :-)9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: Network UPS Tools upsd DSM7-1-42464-211216 - http://www.networkupstools.org/, API v1.2[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Serial Number to "ups"[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Manufacturer to "1"[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Model to "1500"[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Firmware Revision to "1.0.2-0"[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: ups: 1 1500 230V UPS with 24V PbAcid battery from 1[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Outlet In Use to 1[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Total Consumption to 0 kWh[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Log Level to 2[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Last Event to ""[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set On to true[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Current Consumption to 0 W[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Voltage to 237.6 V[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Mute to false[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Status Fault to 0[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180: set Last Event from "" to "undefined"[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Battery Level to 100%[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Charging State to 2[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Status Low Battery to 0[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Low Battery Threshold to 20%[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Charging State from 2 to 0[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Low Battery Threshold from 20% to 10%[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Voltage to 27.1V[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 Battery: set Remaining Duration to 0 seconds[9/30/2022, 6:57:45 PM] [UPS] 192.168.86.180 History: remove stale characteristic Name[9/30/2022, 6:57:45 PM] [UPS] warning: latest version: homebridge-ups v1.0.1[9/30/2022, 6:57:46 PM] [UPS] 192.168.86.180: set Outlet In Use from 1 to trueOn 30 Sep 2022, at 17:49, Erik Baauw ***@***.***> wrote:﻿
Missing device.firmware.  Could you try beta v1.0.2-0?

**Comment by ebaauw** [comment]
Released v1.0.2.

**Comment by eabakker** [comment]
Run Homebridge in docker, so ran ups info from docker shell. Output attached below.

{
  "version": "Network UPS Tools upsd DSM7-1-42464-211216 - http://www.networkupstools.org/",
  "apiVersion": "1.2",
  "devices": {
    "ups": {
      "description": "Unavailable",
      "nCients": "1",
      "clients": [
        "127.0.0.1"
      ],
      "commands": [
        "beeper.disable",
        "beeper.enable",
        "beeper.mute",
        "beeper.off",
        "beeper.on",
        "load.off",
        "load.off.delay",
        "load.on",
        "load.on.delay",
        "shutdown.return",
        "shutdown.stayoff",
        "shutdown.stop",
        "test.battery.start.deep",
        "test.battery.start.quick",
        "test.battery.stop"
      ],
      "constants": {
        "battery.charge": 100,
        "battery.charge.low": 10,
        "battery.charge.warning": 20,
        "battery.mfr.date": 1,
        "battery.runtime": 7200,
        "battery.runtime.low": 300,
        "battery.type": "PbAcid",
        "battery.voltage": "27.1",
        "battery.voltage.nominal": 24,
        "device.mfr": 1,
        "device.model": 1500,
        "device.serial": "",
        "device.type": "ups",
        "driver.name": "usbhid-ups",
        "driver.parameter.pollfreq": 30,
        "driver.parameter.pollinterval": 5,
        "driver.parameter.port": "auto",
        "driver.parameter.synchronous": "no",
        "driver.version": "DSM7-1-42464-211216",
        "driver.version.data": "CyberPower HID 0.4",
        "driver.version.internal": "0.41",
        "input.transfer.high": 290,
        "input.transfer.low": 162,
        "input.voltage": "237.6",
        "input.voltage.nominal": 230,
        "output.voltage": "237.6",
        "ups.beeper.status": "enabled",
        "ups.delay.shutdown": 20,
        "ups.delay.start": 30,
        "ups.load": 0,
        "ups.mfr": 1,
        "ups.model": 1500,
        "ups.productid": 601,
        "ups.realpower.nominal": 900,
        "ups.serial": "",
        "ups.status": "OL",
        "ups.timer.shutdown": -60,
        "ups.timer.start": -60,
        "ups.vendorid": 764
      },
      "variables": {
        "battery.charge.low": 10,
        "battery.runtime.low": 300,
        "input.transfer.high": 290,
        "input.transfer.low": 162,
        "ups.delay.shutdown": 20,
        "ups.delay.start": 30
      }
    }
  }
}
