### ISSUE TITLE
Is it possible to add Battery Percentage as a Sensor?

### ISSUE THREAD

**Issue by milkandbourbons** [ebaauw/homebridge-ups#12]
Both HomeKit App and Eve see the battery percentage and the current Charge State OL, OB, etc
Is it possible to have them exposed as a sensor, like a humidity sensor for example and then automations can be taken on them from within HomeKit, 
For example
When battery percentage falls below "x", turn off switches "a", "b", and, "c".

**Comment by milkandbourbons** [comment]
I've just been and had another read through the ReadME and it does seem like this is already implemented, but my vernacular is off on calling it a sensor.
![image](https://user-images.githubusercontent.com/47081499/217317441-4447988a-0750-47bc-82b9-fe60613f785d.png)

**Comment by ebaauw** [comment]
HomeKit doesn’t know sensors, only accessories (physical devices) and services (logical functions).  Homebridge UPS exposes the battery as a standard _Battery_ service, it’s up to a HomeKit app how to display this.

Siri interacts with services.  Typically, Home shows a tile per service, but there are some exceptions.  Most HomeKit apps treat. _Battery_ special.  Also note that most HomeKit apps, and apparently also the HomeKit UI, take a rather liberal approach and use the label “accessory” for services as well.

**Comment by milkandbourbons** [comment]
Thanks for the clear response.
