### ISSUE TITLE
Log mixes internal/set name

### ISSUE THREAD

**Issue by normen** [ebaauw/homebridge-ups#13]
Hi, first of all thanks for this plugin, its very handy!

I did notice however that the log seems to mix the internal name and the name set manually in HomeKit.

For example this:
```
Mär 05 17:06:20 homebridge homebridge[13036]: [5.3.2023, 17:06:20] [UPS] Eaton Ellipse Regie: Current Consumption: set to 39 W (from 32.5 W)
Mär 05 17:06:50 homebridge homebridge[13036]: [5.3.2023, 17:06:50] [UPS] Eaton Ellipse Regie: Current Consumption: set to 32.5 W (from 39 W)
Mär 05 17:06:50 homebridge homebridge[13036]: [5.3.2023, 17:06:50] [UPS] Eaton Ellipse PRO 650: Voltage: set to 233 V (from 237 V)
Mär 05 17:07:20 homebridge homebridge[13036]: [5.3.2023, 17:07:20] [UPS] Eaton Ellipse PRO 650: Voltage: set to 237 V (from 233 V)
```

`Eaton Ellipse PRO 650` is the NUT-internal name, `Eaton Ellipse Regie` is the name I set in HomeKit via the settings of the UPS switch that your plugin provides. This would not be much of an issue if I had not more than one UPS that are all the same brand/build and thus the `Eaton Ellipse PRO 650` appears multiple times.

Thanks for the attention and thanks again for the plugin!

**Comment by ebaauw** [comment]
I don't think that's technically possible, as both messages are sent through the same log function (which prepends the service name).  Are you sure these changes are for the same UPS?

If they are, could you run Homebridge in DEBUG mode, make sure _Log Level_ is 2 and capture and attach a full log file?

**Comment by normen** [comment]
Okay, thanks for the info, I will check again. Funny thing is I renamed both so if what you say is true then the internal name is still used for one of them.. I'll investigate and report back.

**Comment by normen** [comment]
Uh, well.. Super strange. After a reboot it again calls all of the UPS`s `Eaton Ellipse PRO 650` (internal NUT name) in the log, but the changed names still appear in the Home app.. It seems the names only appear in the log when you change the name and didn't reboot homebridge yet - for some reason. At any instance, I guess this bug report is invalid as is.

Sorry and thanks again for the attention!

**Comment by ebaauw** [comment]
Hm, I would think the service name from HomeKit would be persisted as _Configured Name_ across Homebridge restarts.  But, apparently, I don't update the name of the service delegate.  It's only since iOS 16 that the service name is available to the accessory through _Configured Name_; I'm still figuring out how best to deal with this.

**Comment by ebaauw** [comment]
v1.1.5 should restore the delegate name on Homebridge startup, so the name in the log reflects the service name in HomeKit.
