### ISSUE TITLE
Invalid Name

### ISSUE THREAD

**Issue by elcid2012** [ebaauw/homebridge-ups#14]
Opening this issue up again as I am having the same problem:

I get the following error in the homebridge log after configuring the plugin:

```
[timestamp] [UPS] 10.0.30.6: error: RangeError: : invalid name
    at UpsAccessory.set name [as name] (/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/Delegate.js:132:13)
    at new Delegate (/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/Delegate.js:39:15)
    at new AccessoryDelegate (/homebridge/node_modules/homebridge-ups/node_modules/homebridge-lib/lib/AccessoryDelegate.js:43:5)
    at new UpsAccessory (/homebridge/node_modules/homebridge-ups/lib/UpsAccessory.js:75:5)
    at UpsHost.init (/homebridge/node_modules/homebridge-ups/lib/UpsHost.js:67:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UpsPlatform.init (/homebridge/node_modules/homebridge-ups/lib/UpsPlatform.js:107:7)
```

Using the ups -H command in the terminal connects and displays info of my UPS fine.

I noticed running "ups info" results in the following message:

ups info: error: undefined: connect ECONNREFUSED 127.0.0.1:3493

Config file:

```
            "name": "UPS",
            "hosts": [
                {
                    "host": "10.0.30.6",
                    "username": "upsmon",
                    "password": "secret"
                }
```

It seems the plugin isn't accepting the "host" variable when it's an IP address. If I make my config as such:

```
            "name": "UPS",
            "hosts": [
                {
                    "name": "10.0.30.6",
                    "username": "upsmon",
                    "password": "secret"
                }
```

the homebridge log error goes away. However, ups info still shows ECONNREFUSED on 127.0.0.1:3493.

**Comment by ebaauw** [comment]
You need to specify the host (hostname or ip address and, optionally, port) of the NUT server that Homebridge UPS and/or `ups` connect to.  If you don't, they'll assume it's on the localhost (127.0.0.1) and default port 3439.  Apparently you don't have any service listening to that port, hence the ECONNREFUSED.

I think the RangeError is because the `description` for the UPS is an empty string, `""`, instead of `null` or `"Unavailable"`, and you didn't specify a `name` in config.json.  Double-check by `ups -H 10.0.30.6 info`.

**Comment by elcid2012** [comment]
> I think the RangeError is because the description for the UPS is an empty string, "", instead of null or "Unavailable", and you didn't specify a name in config.json. Double-check by ups -H 10.0.30.6 info.

That is definitely true. I am running ups/nut in another docker container on a macvlan (`upshift/nut-upsd` if anyone else is curious). Let me see if I can figure out how to add a UPS description via environment variable... I don't recall seeing that in the available options.

**Comment by elcid2012** [comment]
Ok, that fixed it. There was an issue with my docker-compose file that wasn't passing the environment variable in correctly, and oddly wasn't erroring/warning in that container's logs.

The error is gone and running `ups -H 10.0.30.6 info` returns the UPS's info properly. Sorry for the confusion on running the `ups info` command by itself without any args. That also makes sense now.

So what we've discovered is the error in the homebridge logs thrown by this plugin are caused by a UPS having an empty string in the description. Indeed, before the fix, the output of

`ups -H 10.0.30.6:3493 info -v`
was

```
{
  "version": "Network UPS Tools upsd 2.7.4 - http://www.networkupstools.org/",
  "apiVersion": "1.2",
  "devices": {
    "network_rack": {
      "description": "",
      "nCients": "1",
      "clients": [
        "127.0.0.1"
      ],
< truncated >
```

**Comment by ebaauw** [comment]
In v1.1.8.
