### ISSUE TITLE
How to configure Homebridge-ups with Synology 

### ISSUE THREAD

**Issue by ismkaya** [ebaauw/homebridge-ups#15]
Hello,

my ups is already configured in Synology DSM 7.2. I try to configure Homebridge-ups but I'm not able to connect it.
This is the error message:
[6/25/2023, 7:49:04 PM] [UPS] DS1: ERR ACCESS-DENIED, API vERR ACCESS-DENIED
[6/25/2023, 7:49:04 PM] [UPS] DS1: warning: recommended version: API v1.2

I would be very pleased if I get help to connect them.

best regards

**Comment by ebaauw** [comment]
Did you follow the steps in the Wiki?

**Comment by ismkaya** [comment]
I guess so...

This is the log, when I restart the UPS-Childbridge:

[6/26/2023, 8:36:19 AM] Registering platform 'homebridge-ups.UPS'
[6/26/2023, 8:36:19 AM] [UPS] Loaded homebridge-ups v1.1.8 child bridge successfully
[6/26/2023, 8:36:19 AM] [UPS] homebridge-ups v1.1.8, node v16.16.0, homebridge v1.6.1, homebridge-lib v6.3.18
[6/26/2023, 8:36:19 AM] [UPS] warning: recommended version: node v18.16.1 LTS
[6/26/2023, 8:36:19 AM] Homebridge v1.6.1 (HAP v0.11.1) (UPS) is running on port 38547.
[6/26/2023, 8:36:19 AM] [UPS] hardware: Synology Synology NAS DS920+
[6/26/2023, 8:36:19 AM] [UPS] os: DSM 7.2-64570 Update 0
[6/26/2023, 8:36:36 AM] [UPS] DS1: warning: timeout after 15s
[6/26/2023, 8:36:36 AM] [UPS] DS1: ERR ACCESS-DENIED, API vERR ACCESS-DENIED
[6/26/2023, 8:36:36 AM] [UPS] DS1: warning: recommended version: API v1.2

**Comment by ebaauw** [comment]
So what’s the output of the commands under _Verify_?

**Comment by ismkaya** [comment]
sh-4.4# upsc -l
Init SSL without certificate database
ups
--------------------------------------
sh-4.4# upsc ups
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.date: 2001/09/25
battery.mfr.date: 2019/11/10
battery.runtime: 5760
battery.runtime.low: 120
battery.type: PbAc
battery.voltage: 27.1
battery.voltage.nominal: 24.0
device.mfr: American Power Conversion
device.model: Back-UPS RS 900G
device.serial: 4B1945P23564  
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 5
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: DSM7-2-60108-221130
driver.version.data: APC HID 0.96
driver.version.internal: 0.41
input.sensitivity: medium
input.transfer.high: 294
input.transfer.low: 176
input.voltage: 237.0
input.voltage.nominal: 230
ups.beeper.status: disabled
ups.delay.shutdown: 20
ups.firmware: 879.L4 .I
ups.firmware.aux: L4  
ups.load: 12
ups.mfr: American Power Conversion
ups.mfr.date: 2019/11/10
ups.model: Back-UPS RS 900G
ups.productid: 0002
ups.realpower.nominal: 540
ups.serial: 4B1945P23564  
ups.status: OL
ups.test.result: No test initiated
ups.timer.reboot: 0
ups.timer.shutdown: -1
ups.vendorid: 051d

**Comment by ebaauw** [comment]
Could, but unlikely.

What the output of `ups info`?  Are you running Homebridge on the Synology as a package or through Docker?   Are you connecting to NUT using `localhost` / `127.0.0.1` or through a hostname / IP address?  Did you enable the network service and whitelist the IP address used by Homebridge?

**Comment by ismkaya** [comment]
the output of "ups info" is:
-sh: ups: command not found

I'm running Homebridge from the synology package. 

changing the host in the configuration from my local ds-ip adress to "localhost" worked.

**Comment by ismkaya** [comment]
ups -info (on hb-console):

homebridge@ds1:/etc/ups $ ups info
{
  "version": "Network UPS Tools upsd DSM7-2-60108-221130 - http://www.networkupstools.org/",
  "apiVersion": "1.2",
  "devices": {
    "ups": {
      "description": "Unavailable",
      "nCients": "2",
      "clients": [
        "127.0.0.1",
        "192.168.1.220"
      ],
      "commands": [
        "beeper.disable",
        "beeper.enable",
        "beeper.mute",
        "beeper.off",
        "beeper.on",
        "load.off",
        "load.off.delay",
        "shutdown.reboot",
        "shutdown.stop",
        "test.battery.start.deep",
        "test.battery.start.quick",
        "test.battery.stop",
        "test.panel.start",
        "test.panel.stop"
      ],
      "constants": {
        "battery.charge": "100",
        "battery.charge.low": "10",
        "battery.charge.warning": "50",
        "battery.date": "2001/09/25",
        "battery.mfr.date": "2019/11/10",
        "battery.runtime": "5760",
        "battery.runtime.low": "120",
        "battery.type": "PbAc",
        "battery.voltage": "27.1",
        "battery.voltage.nominal": "24.0",
        "device.mfr": "American Power Conversion",
        "device.model": "Back-UPS RS 900G",
        "device.serial": "4B1945P23564",
        "device.type": "ups",
        "driver.name": "usbhid-ups",
        "driver.parameter.pollfreq": "30",
        "driver.parameter.pollinterval": "5",
        "driver.parameter.port": "auto",
        "driver.parameter.synchronous": "no",
        "driver.version": "DSM7-2-60108-221130",
        "driver.version.data": "APC HID 0.96",
        "driver.version.internal": "0.41",
        "input.sensitivity": "medium",
        "input.transfer.high": "294",
        "input.transfer.low": "176",
        "input.voltage": "237.0",
        "input.voltage.nominal": "230",
        "ups.beeper.status": "disabled",
        "ups.delay.shutdown": "20",
        "ups.firmware": "879.L4 .I",
        "ups.firmware.aux": "L4",
        "ups.load": "12",
        "ups.mfr": "American Power Conversion",
        "ups.mfr.date": "2019/11/10",
        "ups.model": "Back-UPS RS 900G",
        "ups.productid": "0002",
        "ups.realpower.nominal": "540",
        "ups.serial": "4B1945P23564",
        "ups.status": "OL",
        "ups.test.result": "No test initiated",
        "ups.timer.reboot": "0",
        "ups.timer.shutdown": "-1",
        "ups.vendorid": "051d"
      },
      "variables": {
        "battery.charge.low": "10",
        "battery.runtime.low": "120",
        "input.sensitivity": "medium",
        "input.transfer.high": "294",
        "input.transfer.low": "176",
        "ups.delay.shutdown": "20"
      }
    }
  }
}

**Comment by ebaauw** [comment]
> changing the host in the configuration from my local ds-ip adress to "localhost" worked.

I think, if you use the external IP address, instead of `localhost` or `127.0.0.1`, NUT will treat it as a network connection, requiring a whitelist entry.
