### ISSUE TITLE
log level setting

### ISSUE THREAD

**Issue by maximilanna** [ebaauw/homebridge-ups#16]
Thank you for making this plugin, I love it. The only thing i'd add is a log level setting. For example, i would only like to see warnings or errors in my normal homebridge log - vs things like: Voltage: set to 123 V (from 121 V). Is that something thats easy to add?

**Comment by ebaauw** [comment]
It's already there: you can set the log level per accessory from HomeKit.  You do need a decent HomeKit app for that, as Apple's Home doesn't support custom services nor characteristics.
