### ISSUE TITLE
Anoying message in homebridge console: Upsilon 2000 Battery: Remaining Duration: get: return 0 seconds

### ISSUE THREAD

**Issue by pcontezini** [ebaauw/homebridge-ups#18]
Hello, i'm using the latest version of homebridge-ups, connected to a UPS in a remote machine.

In the constants area of the debugger command, it says that the battery.runtime is 1200 seconds.

But in the homebridge console, it keeps saying this:

[27/11/2023, 14:55:16] [UPS] Upsilon 2000 Battery: Remaining Duration: get: return 0 seconds
[27/11/2023, 14:55:16] [UPS] Upsilon 2000 Battery: Remaining Duration: get: return 0 seconds
[27/11/2023, 14:55:20] [UPS] Upsilon 2000 Battery: Remaining Duration: get: return 0 seconds

This is the dump of the ups connecting to the server:

{
  "version": "Network UPS Tools upsd 2.7.4 - http://www.networkupstools.org/",
  "apiVersion": "1.2",
  "devices": {
    "upsilon-2000": {
      "description": "Upsilon 2000",
      "nCients": "0",
      "clients": [],
      "commands": [
        "beeper.toggle",
        "load.off",
        "load.on",
        "shutdown.return",
        "shutdown.stayoff",
        "shutdown.stop",
        "test.battery.start",
        "test.battery.start.deep",
        "test.battery.start.quick",
        "test.battery.stop"
      ],
      "constants": {
        "battery.charge": "100",
        "battery.runtime": "1200",
        "battery.voltage": "82.08",
        "battery.voltage.high": "78.00",
        "battery.voltage.low": "62.40",
        "battery.voltage.nominal": "72.0",
        "device.mfr": "",
        "device.model": "",
        "device.type": "ups",
        "driver.name": "blazer_usb",
        "driver.parameter.langid_fix": "0x409",
        "driver.parameter.pollinterval": "2",
        "driver.parameter.port": "auto",
        "driver.parameter.productid": "0000",
        "driver.parameter.runtimecal": "120,100,350,50",
        "driver.parameter.synchronous": "no",
        "driver.parameter.vendorid": "0001",
        "driver.version": "2.7.4",
        "driver.version.internal": "0.12",
        "input.current.nominal": "13.0",
        "input.frequency": "60.1",
        "input.frequency.nominal": "60",
        "input.voltage": "222.1",
        "input.voltage.fault": "227.0",
        "input.voltage.nominal": "220",
        "output.voltage": "220.5",
        "ups.beeper.status": "disabled",
        "ups.delay.shutdown": "30",
        "ups.delay.start": "180",
        "ups.firmware": "V13",
        "ups.load": "10",
        "ups.mfr": "",
        "ups.model": "",
        "ups.productid": "0000",
        "ups.status": "OL",
        "ups.temperature": "25.0",
        "ups.type": "online",
        "ups.vendorid": "0001"
      },
      "variables": {}
    }
  }
}

**Comment by ebaauw** [comment]
By design, Homebridge UPS returns 0 when on mains power.  When on battery power, it shows the (expected) remaining time.

Set _LogLevel_ to 0 to suppress the log messages.

**Comment by irctrakz** [comment]
Dumb question: Where does one set _LogLevel_ to 0? This isn't a Homebridge config option is it?

**Comment by ebaauw** [comment]
On the UPS accessory.  You need a decent HomeKit app for that, as Apple’s Home app doesn’t support custom services nor characteristics.

**Comment by pcontezini** [comment]
> On the UPS accessory.  You need a decent HomeKit app for that, as Apple’s Home app doesn’t support custom services nor characteristics.

Can you point me to the name of one app that supports this? Thanks!

**Comment by sapireli** [comment]
Try “controller” its my favorite.
