### ISSUE TITLE
UPS is missing ups.firmware

### ISSUE THREAD

**Issue by dacarson** [ebaauw/homebridge-ups#2]
Thanks for the great plugin. It is failing for me because my UPS doesn't report a ups.firmware field. Below are all my parameters.

Name | : | Value
-- | -- | --
battery.charge | : | 2
battery.charge.low | : | 10
battery.charge.warning | : | 20
battery.mfr.date | : | CPS
battery.runtime | : | 61
battery.runtime.low | : | 300
battery.type | : | PbAcid
battery.voltage | : | 24.0
battery.voltage.nominal | : | 24
device.mfr | : | CPS
device.model | : | CP1500PFCLCD
device.serial | : | 000000000000
device.type | : | ups
driver.name | : | usbhid-ups
driver.parameter.pollfreq | : | 30
driver.parameter.pollinterval | : | 2
driver.parameter.port | : | auto
driver.parameter.productid | : | 0501
driver.parameter.serial | : | 000000000000
driver.parameter.synchronous | : | no
driver.parameter.vendorid | : | 0764
driver.version | : | 2.7.4
driver.version.data | : | CyberPower HID 0.4
driver.version.internal | : | 0.41
input.transfer.high | : | 139
input.transfer.low | : | 88
input.voltage | : | 124.0
input.voltage.nominal | : | 120
output.voltage | : | 140.0
ups.beeper.status | : | disabled
ups.delay.shutdown | : | 20
ups.delay.start | : | 30
ups.load | : | 14
ups.mfr | : | CPS
ups.model | : | CP1500PFCLCD
ups.productid | : | 0501
ups.realpower.nominal | : | 900
ups.serial | : | 000000000000
ups.status | : | OL CHRG LB
ups.test.result | : | No test initiated
ups.timer.shutdown | : | -60
ups.timer.start | : | -60
ups.vendorid | : | 0764

So UpsHost.js may need a line such as:
         const firmware = constants['ups.firmware'] == null || constants['ups.firmware'] === '' ? 'Unknown' : constants['ups.firmware'].trim()

**Comment by ebaauw** [comment]
That is already in beta v1.0.2-0.

**Comment by ebaauw** [comment]
Released v1.0.2.
