### ISSUE TITLE
When the battery is discharging, HomeKit still shows it as charging.

### ISSUE THREAD

**Issue by dacarson** [ebaauw/homebridge-ups#3]
When the UPS reports:
"ups.status": "OB DISCHRG",
I still see the battery charging in HomeKit. 

As mentioned in the header UpsClient.js:
/* Possible values for `ups.state`:
 * OL      - On line (mains is present)
 * OB      - On battery (mains is not present)
 * LB      - Low battery
 * HB      - High battery
 * RB      - The battery needs to be replaced
 * CHRG    - The battery is charging
 * DISCHRG - The battery is discharging (inverter is providing load power)
 * BYPASS  - UPS bypass circuit is active - no battery protection is available
 * CAL     - UPS is currently performing runtime calibration (on battery)
 * OFF     - UPS is offline and is not supplying power to the load
 * OVER    - UPS is overloaded
 * TRIM    - UPS is trimming incoming voltage (called "buck" in some hardware)
 * BOOST   - UPS is boosting incoming voltage
 * FSD     - Forced Shutdown (restricted use, see the note below)
 */

I think the problem is in this line of code in UpsService.js:
    this.values.chargingState = constants['ups.status'].includes('CHRG')
      ? this.Characteristics.hap.ChargingState.CHARGING
      : this.Characteristics.hap.ChargingState.NOT_CHARGING
      
As DISCHRG does include CHRG, it is returning that it is charging.

**Comment by ebaauw** [comment]
Good find.

**Comment by ebaauw** [comment]
Could you try beta v1.0.3-0?  All checks of `ups.status` should now only match a whole word.

**Comment by dacarson** [comment]
Tested 1.0.3-1 and it is no longer showing the battery as charging when power is lost.

**Comment by ebaauw** [comment]
Published v1.0.3.
