### ISSUE TITLE
When the UPS has no mains power, HomeKit reports input voltage as 100v

### ISSUE THREAD

**Issue by dacarson** [ebaauw/homebridge-ups#4]
When my UPS looses mains voltage, I see in the Eve app the voltage doesn't drop to zero, rather it shows 100v.

Checking 'ups info' I see:
`        "input.voltage": "0.0",
        "input.voltage.nominal": "120",
        "output.voltage": "136.0",`
I suspect the problem is because the Homebridge-lib defines the Eve voltage characteristic as:

>     this.createCharacteristicClass('Voltage', uuid('10A'), {
> 
>       format: this.Formats.FLOAT,
>       unit: 'V',
>       minValue: 100,
>       maxValue: 250,
>       minStep: 0.1,
>       perms: [this.Perms.READ, this.Perms.NOTIFY]
>     })

And then in the Outlet class, this characteristic is used:

>     this.addCharacteristicDelegate({
>       key: 'voltage',
>       Characteristic: this.Characteristics.eve.Voltage,
>       unit: ' V'
>     })

As such, the 0.0 value coming from 'ups info' is set to the minimum, which is 100.

**Comment by ebaauw** [comment]
Not sure where the minimum value came from (or the maximum for that matter).  Probably that's how the Eve Energy exposes it.  Anyway, I can overwrite the properties in Homebridge UPS.

**Comment by ebaauw** [comment]
Could you try beta v1.0.3-0?  Also made the parsing of UPS state more robust to deal with different UPS models reporting different constants.

**Comment by ebaauw** [comment]
I think I already published a later beta, just specify `homebridge-ups@beta`.

**Comment by ebaauw** [comment]
Published v1.0.3
