### ISSUE TITLE
Total Consumption should be in Wh or divided by 1000.

### ISSUE THREAD

**Issue by alexp999** [ebaauw/homebridge-ups#6]
My current usage is being reported as 35-40W, but the total consumption is going up 5-6 kWh every 10 mins, instead of 5-6 Wh or 0.005-0.006 kWh every 10 mins. So my 35-40W load is reporting 2500 kWh total usage after only a couple of days.

**Comment by ebaauw** [comment]
Yes, see https://github.com/ebaauw/homebridge-ups/issues/5#issuecomment-1284456389
